name = "sdlada_mixer"
description = "Ada 2022 bindings to SDL2_mixer."
version = "2.5.22"

authors = ["Luke A. Guest"]
maintainers = ["Luke A. Guest <laguest@archeia.com>"]
maintainers-logins = ["Lucretia"]
licenses = "Zlib"
website = ""
tags = ["sdl2", "mixer", "audio"]

[[depends-on]]
  sdlada = "=2.5.23"
  libsdl2_mixer = "^2.0.0"

[[pins]] # TODO: Remove
  sdlada = { path = "../sdlada" }

