---

name: CI Windows

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: CI on windows

    runs-on: windows-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: alire-project/setup-alire
      uses: alire-project/setup-alire@v2
    -
      name: Install toolchain
      run: |
        alr --non-interactive config --global --set toolchain.assistant false
        alr --non-interactive toolchain --install gnat_native
        alr --non-interactive toolchain --install gprbuild
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    -
      name: Build and run
      run: |
        alr --non-interactive build
